packages:
  - packages/*
  - playground
  - docs
catalog:
  '@antfu/eslint-config': ^3.12.0
  '@types/gulp': ^4.0.17
  '@types/node': ^22.13.13
  '@unocss/eslint-plugin': ^66.0.0
  '@unocss/preset-mini': ^66.0.0
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/tsconfig': ^0.7.0
  bumpp: ^10.1.0
  eslint: ^9.23.0
  eslint-plugin-format: ^1.0.0
  gulp: ^5.0.0
  gulp-cli: ^3.0.0
  husky: ^9.1.7
  lint-staged: ^15.5.0
  magic-color: ^2.0.0
  rollup-plugin-copy: ^3.5.0
  sucrase: ^3.35.0
  typescript: ^5.8.2
  unocss: ^66.0.0
  unocss-preset-ctx: ^1.2.0
  vite: ^6.2.3
  vite-plugin-dts: ^4.5.3
  vitepress: ^1.5.0
  vitepress-demo-plugin: ^1.2.2
  vue: ^3.5.13
  vue-tsc: ^2.2.8
