packages:
  - packages/*/**
  - playground
  - docs
catalog:
  "@antfu/eslint-config": ^3.12.0
  "@types/gulp": ^4.0.17
  "@types/node": ^22.10.2
  "@unocss/eslint-plugin": ^0.65.2
  "@unocss/preset-mini": ^0.65.2
  "@vitejs/plugin-vue": ^5.2.1
  "@vue/tsconfig": ^0.7.0
  bumpp: ^9.9.2
  eslint: ^9.17.0
  eslint-plugin-format: ^0.1.3
  gulp: ^5.0.0
  gulp-cli: ^3.0.0
  husky: ^9.1.7
  lint-staged: ^15.2.11
  magic-color: ^2.0.0
  rollup-plugin-copy: ^3.5.0
  sucrase: ^3.35.0
  typescript: ^5.7.2
  unocss: ^0.65.2
  vite: ^6.0.5
  vite-plugin-dts: ^4.4.0
  vue: ^3.5.13
  vue-tsc: ^2.1.10
